<?php $this->placeholder('content')->captureStart(); ?>
<?php
	foreach	($this->tree as	$item):
?>
	<div class="content_body_item">
		<h2><?php echo $item['obj']->name; ?></h2>
		<ul>
			<li><a href="<?php echo	$this->baseUrl($this->navigation()->findOneById('user_collections')->getUri()	.	$item['obj']->name); ?>/items/">items</a><br/>
			<li><a href="<?php echo	$this->baseUrl($this->navigation()->findOneById('user_collections')->getUri()	.	$item['obj']->name); ?>/datasources/">datasources</a>
		</ul>
	</div>
<?php
	endforeach;
?>
<?php $this->placeholder('content')->captureEnd(); ?>
	<div id="content"><div id="content_body">
<?php	echo $this->placeholder('content'); ?>
	</div></div>
<?php 
	echo $this->partial('leftTab.phtml', array(
		'user' => $this->user, 
		'tree' => $this->tree)); 
?>
	<script>
		Ext.get('content').set({style: {display: 'none'}});
		var bodyItems = [leftTab,
			{
				xtype: 'panel',
				title: 'Welcome, <?php echo addslashes($this->user->fullname); ?>',
				region: 'center',
				margins: '5 5 5 0',
				contentEl: 'content_body'
			}];
	</script>